<a href="https://colab.research.google.com/github/estebanszd/Clase-Introducci-n-/blob/main/Limpieza_de_datos_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/mnt/drive')

Mounted at /mnt/drive

In [ ]:
import os
os.chdir("/mnt/drive/MyDrive/ciencia_de_datos")

In [ ]:
print(os.listdir())

['netflix_data.csv', 'Untitled0.ipynb', 'stations.p', 'actors_movies.csv', 'casts.p', 'crews.p', 'taglines.p', 'S&P500.csv', 'WorldBank_GDP.csv', 'WorldBank_POP.csv', 'taxi_owners.csv', 'taxi_vehicles.csv', 'Chicago_wards.csv', 'Chicago_census.csv', 'licenses.csv', 'zip_demo.csv', 'business_owners.csv', 'land_use.csv', 'cta_ridership.csv', 'cta_calendar.csv', 'movies.csv', 'ratings.csv', 'movie_to_genres.csv', 'sequels.csv', 'financials.csv', 'biometria.csv', 'police.csv', 'policies.parquet', 'billboard.csv', 'datos_crudos.csv', 'datos_crudos_tarea.csv', 'datos_limpios.csv']

In [ ]:
os.listdir()

['netflix_data.csv',
 'Untitled0.ipynb',
 'stations.p',
 'actors_movies.csv',
 'casts.p',
 'crews.p',
 'taglines.p',
 'S&P500.csv',
 'WorldBank_GDP.csv',
 'WorldBank_POP.csv',
 'taxi_owners.csv',
 'taxi_vehicles.csv',
 'Chicago_wards.csv',
 'Chicago_census.csv',
 'licenses.csv',
 'zip_demo.csv',
 'business_owners.csv',
 'land_use.csv',
 'cta_ridership.csv',
 'cta_calendar.csv',
 'movies.csv',
 'ratings.csv',
 'movie_to_genres.csv',
 'sequels.csv',
 'financials.csv',
 'biometria.csv',
 'police.csv',
 'policies.parquet',
 'billboard.csv',
 'datos_crudos.csv',
 'datos_crudos_tarea.csv',
 'datos_limpios.csv']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.DataFrame({"Property": ["House 1", "House 2", "House 3"],
                   "Price": [0.8,0.4,0.8],
                   "Space": [0.6,0.3,0.7],
                   "Location": [0.99,0.2,0.4],
                   "Aesthetics": [0.5,0.6,0.8]
})

In [ ]:
df.head()

  Property  Price  Space  Location  Aesthetics
0  House 1    0.8    0.6      0.99         0.5
1  House 2    0.4    0.3      0.20         0.6
2  House 3    0.8    0.7      0.40         0.8

In [ ]:
columnas = df.columns
print(f"Las columnas de la dataframe son: {columnas}")

print(120*"*")
columnas_a_fusionar = columnas[1:5]
print(f"las columnas a fusionar son: {columnas_a_fusionar}")

Las columnas de la dataframe son: Index(['Property', 'Price', 'Space', 'Location', 'Aesthetics'], dtype='object')
************************************************************************************************************************
las columnas a fusionar son: Index(['Price', 'Space', 'Location', 'Aesthetics'], dtype='object')

In [ ]:
df_long = pd.melt(frame= df, id_vars = "Property"  ,value_vars=columnas_a_fusionar)

In [ ]:
df_long

   Property    variable  value
0   House 1       Price   0.80
1   House 2       Price   0.40
2   House 3       Price   0.80
3   House 1       Space   0.60
4   House 2       Space   0.30
5   House 3       Space   0.70
6   House 1    Location   0.99
7   House 2    Location   0.20
8   House 3    Location   0.40
9   House 1  Aesthetics   0.50
10  House 2  Aesthetics   0.60
11  House 3  Aesthetics   0.80

In [ ]:
billboard = pd.read_csv("billboard.csv")

In [ ]:
billboard.head()

,artist,track,date.entered,wk1,wk2,wk3,wk4,wk5,wk6,wk7,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2 Pac,Baby Don't Cry (Keep...,2000-02-26,87,82.0,72.0,77.0,87.0,94.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2Ge+her,The Hardest Part Of ...,2000-09-02,91,87.0,92.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3 Doors Down,Kryptonite,2000-04-08,81,70.0,68.0,67.0,66.0,57.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3 Doors Down,Loser,2000-10-21,76,76.0,72.0,69.0,67.0,65.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,504 Boyz,Wobble Wobble,2000-04-15,57,34.0,25.0,17.0,17.0,31.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
columns_bill = billboard.columns

In [ ]:
billboard.shape

(317, 79)

In [ ]:
columns_bill

Index(['artist', 'track', 'date.entered', 'wk1', 'wk2', 'wk3', 'wk4', 'wk5',
       'wk6', 'wk7', 'wk8', 'wk9', 'wk10', 'wk11', 'wk12', 'wk13', 'wk14',
       'wk15', 'wk16', 'wk17', 'wk18', 'wk19', 'wk20', 'wk21', 'wk22', 'wk23',
       'wk24', 'wk25', 'wk26', 'wk27', 'wk28', 'wk29', 'wk30', 'wk31', 'wk32',
       'wk33', 'wk34', 'wk35', 'wk36', 'wk37', 'wk38', 'wk39', 'wk40', 'wk41',
       'wk42', 'wk43', 'wk44', 'wk45', 'wk46', 'wk47', 'wk48', 'wk49', 'wk50',
       'wk51', 'wk52', 'wk53', 'wk54', 'wk55', 'wk56', 'wk57', 'wk58', 'wk59',
       'wk60', 'wk61', 'wk62', 'wk63', 'wk64', 'wk65', 'wk66', 'wk67', 'wk68',
       'wk69', 'wk70', 'wk71', 'wk72', 'wk73', 'wk74', 'wk75', 'wk76'],
      dtype='object')

In [ ]:
billboard_long = pd.melt(billboard, id_vars=["artist","track", "date.entered"], value_vars=columns_bill[3:80])
billboard_long.tail()

                 artist                    track date.entered variable  value
24087       Yankee Grey     Another Nine Minutes   2000-04-29     wk76    NaN
24088  Yearwood, Trisha          Real Live Woman   2000-04-01     wk76    NaN
24089   Ying Yang Twins  Whistle While You Tw...   2000-03-18     wk76    NaN
24090     Zombie Nation            Kernkraft 400   2000-09-02     wk76    NaN
24091   matchbox twenty                     Bent   2000-04-29     wk76    NaN

In [ ]:
billboard_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24092 entries, 0 to 24091
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   artist        24092 non-null  object
 1   track         24092 non-null  object
 2   date.entered  24092 non-null  object
 3   variable      24092 non-null  object
 4   value         5307 non-null   float64
dtypes: float64(1), object(4)
memory usage: 941.2+ KB

In [ ]:
billboard_long.shape

(24092, 5)

In [ ]:
billboard_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24092 entries, 0 to 24091
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   artist        24092 non-null  object
 1   track         24092 non-null  object
 2   date.entered  24092 non-null  object
 3   variable      24092 non-null  object
 4   value         5307 non-null   float64
dtypes: float64(1), object(4)
memory usage: 941.2+ KB

In [ ]:
billboard_long["date.entered"] = pd.to_datetime(billboard_long["date.entered"])

In [ ]:
billboard_long["year"] = billboard_long["date.entered"].dt.year
billboard_long["month"] = billboard_long["date.entered"].dt.month
billboard_long["week"] = billboard_long["date.entered"].dt.isocalendar().week

In [ ]:
billboard_long["value"].dropna(inplace=True)

Tarea:
Luego de haber hecho +
correo = esteban2005sep@gmail.com
contraseña = Alfonzodiaz12345
buscar salud mental 19 dic 2025
descargar datos
tipo de enfermedad mas reportada por edad

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
datos_crudos = pd.read_csv("/content/drive/MyDrive/ciencia_de_datos/datos_crudos.csv")

In [ ]:
datos_crudos.head()

,Unnamed: 0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [ ]:
df = datos_crudos.copy()

In [ ]:
print(df.shape)
print(110* "*")
print(df.dtypes)
print(110* "*")
print(df.isnull().sum())
print(110* "*")
print(df.duplicated().sum())
print(110* "*")
df.head()

(30, 11)
**************************************************************************************************************
Unnamed: 0          int64
id_paciente         int64
nombre             object
edad              float64
sexo               object
diagnostico        object
peso_kg           float64
fecha_ingreso      object
fecha_alta         object
costo_usd          object
n_medicamentos    float64
dtype: object
**************************************************************************************************************
Unnamed: 0        0
id_paciente       0
nombre            0
edad              1
sexo              0
diagnostico       0
peso_kg           2
fecha_ingreso     0
fecha_alta        0
costo_usd         0
n_medicamentos    1
dtype: int64
**************************************************************************************************************
0
**************************************************************************************************************

,Unnamed: 0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [ ]:
#Eliminación de duplicados+
print(f"filas antes: {df.shape[0]}")
df = df.drop_duplicates()
print(f"Filas después: {df.shape[0]}")

filas antes: 30
Filas después: 30

In [ ]:
datos_crudos.columns

Index(['Unnamed: 0', 'id_paciente', 'nombre', 'edad', 'sexo', 'diagnostico',
       'peso_kg', 'fecha_ingreso', 'fecha_alta', 'costo_usd',
       'n_medicamentos'],
      dtype='object')

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.encode("ascii", errors="ignores")
    .str.decode("ascii")
)
print(df.columns.tolist())

['unnamed:_0', 'id_paciente', 'nombre', 'edad', 'sexo', 'diagnostico', 'peso_kg', 'fecha_ingreso', 'fecha_alta', 'costo_usd', 'n_medicamentos']

In [ ]:
df.head()

,unnamed:_0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25.0,M,F412,70.0,2023-01-15,2023-01-20,"$1,200",3.0
1,1,2,maría lopez,34.0,F,F322,58.0,15/02/2023,2023-02-10,$850.50,2.0
2,2,3,PEDRO MARTINEZ,-5.0,m,F321,82.0,2023-03-20,2023-03-15,1500,1.0
3,3,4,Ana Ruiz,128.0,f,F319,91.0,20-04-2023,2023-04-25,"$2,300",4.0
4,4,5,carlos GOMEZ,45.0,Masculino,f209,NaN,2023/05/10,2023-05-08,900,NaN

In [ ]:
var1 = "EDaD "

In [ ]:
var1.strip().lower()

'edad'

In [ ]:
#Nombre: capitalización consistente
df["nombre"] = df["nombre"].str.strip().str.title()
#Diagnóstico: Mayúsculas sin espacios
df["diagnostico"] = df["diagnostico"].str.strip().str.upper()
#Sexo: unificar categorías antes de convertir
mapa_sexo = {
    "m": "M", "masculino": "M",
    "f": "F", "femenino": "F",
    "999": np.nan
}
df["sexo"] = df["sexo"].str.strip().str.lower().map(mapa_sexo)
print(df["sexo"].value_counts(dropna=False))

sexo
F      15
M      14
NaN     1
Name: count, dtype: int64

In [ ]:
#peso_kg: reemplazar "N/A" string antes de convertir
df['peso_kg'] = df['peso_kg'].replace('N/A', np.nan)
df['peso_kg'] = pd.to_numeric(df['peso_kg'], errors='coerce')

#costo_usd: eeliminar $ y comas
df['costo_usd'] = (
    df['costo_usd']
    .str.replace('$', '', regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    )
df['costo_usd'] = pd.to_numeric(df['costo_usd'], errors='coerce')
print(df[["peso_kg", "costo_usd"]].dtypes)

peso_kg      float64
costo_usd    float64
dtype: object

In [153]:
df["fecha_ingreso"] = pd.to_datetime(df["fecha_ingreso"], dayfirst=False, errors="coerce")
df["fecha_alta"] = pd.to_datetime(df["fecha_alta"], dayfirst=False, errors="coerce")

In [143]:
# Limpiar y convertir 'edad': descartar valores fuera de 0-105, mantener NaN y convertir a entero (nullable)
df['edad'] = df['edad'].apply(lambda x: x if 0 <= x <= 105 else np.nan)
# Calcular el promedio de edad antes de llenar los NaN
mean_edad = df['edad'].mean()
# Llenar los NaN con el promedio de edad (redondeado para la conversión a Int64Dtype)
df['edad'] = df['edad'].fillna(round(mean_edad))
df['edad'] = df['edad'].astype(pd.Int64Dtype())

# Limpiar y convertir 'n_medicamentos': rellenar NaN con 0 y convertir a entero
df['n_medicamentos'] = df['n_medicamentos'].fillna(0).astype(int)

In [154]:
df.head()

,unnamed:_0,id_paciente,nombre,edad,sexo,diagnostico,peso_kg,fecha_ingreso,fecha_alta,costo_usd,n_medicamentos
0,0,1,Juan García,25,M,F412,70.0,2023-01-15,2023-01-20,1200.0,3
1,1,2,María Lopez,34,F,F322,58.0,NaT,2023-02-10,850.5,2
2,2,3,Pedro Martinez,41,M,F321,82.0,2023-03-20,2023-03-15,1500.0,1
3,3,4,Ana Ruiz,41,F,F319,91.0,NaT,2023-04-25,2300.0,4
4,4,5,Carlos Gomez,45,M,F209,NaN,NaT,2023-05-08,900.0,0