<a href="https://colab.research.google.com/github/estebanszd/Clase-Introducci-n-/blob/main/Tarea_Datos_Abiertos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("/content/Salud_Mental_20260413.csv")

In [9]:
df.head()

,diagnostico_ingreso,codigo_dx_ingreso,Menor a 1,De 1 a 4,De 5 a 9,De 10 a 14,De 15 a 19,De 20 a 49,De 50 a 64,65 Y MAS,Total,Año diagnóstico
0,TRASTORNO MIXTO DE ANSIEDAD Y DEPRESION,F412,0,0,0,10,9,31,8,2,60,2023
1,EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS,F322,0,0,0,10,10,31,4,3,58,2023
2,EPISODIO DEPRESIVO MODERADO,F321,0,0,0,3,2,11,1,4,21,2023
3,"TRASTORNO AFECTIVO BIPOLAR, NO ESPECIFICADO",F319,0,0,0,1,1,12,4,1,19,2023
4,"ESQUIZOFRENIA, NO ESPECIFICADA",F209,0,0,0,1,0,14,0,0,15,2023

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   diagnostico_ingreso  142 non-null    object
 1   codigo_dx_ingreso    142 non-null    object
 2   Menor a 1            142 non-null    int64
 3   De 1 a 4             142 non-null    int64
 4   De 5 a 9             142 non-null    int64
 5   De 10 a 14           142 non-null    int64
 6   De 15 a 19           142 non-null    int64
 7   De 20 a 49           142 non-null    int64
 8   De 50 a 64           142 non-null    int64
 9   65 Y MAS             142 non-null    int64
 10  Total                142 non-null    int64
 11  Año diagnóstico      142 non-null    int64
dtypes: int64(10), object(2)
memory usage: 13.4+ KB

In [11]:
df.isnull().sum()

diagnostico_ingreso    0
codigo_dx_ingreso      0
Menor a 1              0
De 1 a 4               0
De 5 a 9               0
De 10 a 14             0
De 15 a 19             0
De 20 a 49             0
De 50 a 64             0
65 Y MAS               0
Total                  0
Año diagnóstico        0
dtype: int64

In [12]:
print(df.corr(numeric_only=True))

                 Menor a 1  De 1 a 4  De 5 a 9  De 10 a 14  De 15 a 19  \
Menor a 1         1.000000 -0.007092 -0.014338   -0.024030   -0.025084
De 1 a 4         -0.007092  1.000000 -0.014338   -0.024030   -0.025084
De 5 a 9         -0.014338 -0.014338  1.000000    0.600451    0.576639
De 10 a 14       -0.024030 -0.024030  0.600451    1.000000    0.926953
De 15 a 19       -0.025084 -0.025084  0.576639    0.926953    1.000000
De 20 a 49       -0.024099 -0.024099  0.235232    0.713528    0.695739
De 50 a 64       -0.034678 -0.034678  0.131683    0.534651    0.514470
65 Y MAS         -0.031926 -0.031926 -0.025487    0.135823    0.120823
Total            -0.024413 -0.024413  0.422826    0.884362    0.870467
Año diagnóstico   0.066959 -0.105918  0.004307   -0.056552   -0.065807

                 De 20 a 49  De 50 a 64  65 Y MAS     Total  Año diagnóstico
Menor a 1         -0.024099   -0.034678 -0.031926 -0.024413         0.066959
De 1 a 4          -0.024099   -0.034678 -0.031926 -0.024413        -0.105918
De 5 a 9           0.235232    0.131683 -0.025487  0.422826         0.004307
De 10 a 14         0.713528    0.534651  0.135823  0.884362        -0.056552
De 15 a 19         0.695739    0.514470  0.120823  0.870467        -0.065807
De 20 a 49         1.000000    0.747237  0.170206  0.925497        -0.017967
De 50 a 64         0.747237    1.000000  0.231949  0.760028        -0.163781
65 Y MAS           0.170206    0.231949  1.000000  0.326094        -0.052313
Total              0.925497    0.760028  0.326094  1.000000        -0.064940
Año diagnóstico   -0.017967   -0.163781 -0.052313 -0.064940         1.000000

In [15]:
# Define las columnas que representan los grupos de edad.
columnas_edad = ['Menor a 1', 'De 1 a 4', 'De 5 a 9', 'De 10 a 14', 'De 15 a 19', 'De 20 a 49', 'De 50 a 64', '65 Y MAS']

# Imprime un encabezado para la salida.
print("Enfermedad más común por grupo de edad:")

# Itera sobre cada columna de grupo de edad.
for columna in columnas_edad:
    # Filtra el DataFrame para las filas donde hay casos en el grupo de edad actual.
    df_filtrado = df[df[columna] > 0]

    # Encuentra el diagnóstico más común para el grupo de edad filtrado.
    diagnostico_principal = df_filtrado.groupby('diagnostico_ingreso')[columna].sum().idxmax()

    # Obtiene la cantidad de casos para ese diagnóstico principal.
    conteo_maximo = df_filtrado.groupby('diagnostico_ingreso')[columna].sum().max()

    # Imprime el resultado para el grupo de edad actual.
    print(f"  Grupo de Edad: {columna}: {diagnostico_principal} (Cantidad: {conteo_maximo})")

Enfermedad más común por grupo de edad:
  Grupo de Edad: Menor a 1: CONVULSIONES DISOCIATIVAS (Cantidad: 1)
  Grupo de Edad: De 1 a 4: CONVULSIONES DISOCIATIVAS (Cantidad: 1)
  Grupo de Edad: De 5 a 9: EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS (Cantidad: 3)
  Grupo de Edad: De 10 a 14: EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS (Cantidad: 31)
  Grupo de Edad: De 15 a 19: EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS (Cantidad: 33)
  Grupo de Edad: De 20 a 49: EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS (Cantidad: 54)
  Grupo de Edad: De 50 a 64: TRASTORNO MIXTO DE ANSIEDAD Y DEPRESION (Cantidad: 13)
  Grupo de Edad: 65 Y MAS: DELIRIO, NO ESPECIFICADO (Cantidad: 23)